#!/usr/bin/env python3
"""
update_ist_coefficients.py - Apply SMELT Coefficients to IST Settings
======================================================================

Reads a smelt_update_config.json (generated by generate_smelt_config.py),
applies real SMELT-fitted coefficients to ist_settings.pm VFE tables, and
produces updated .pm and .xlsx output files.

Supports multiple IST families: MATHS-IST, RIST, RIST-Adaptive.
Each family has its own handler module that implements parsing, planning,
and Perl text generation.

Workflow:
  Step 1 - Generate config:
    python scripts/generate_smelt_config.py -o config/smelt_update_config.json

  Step 2 - Review & edit config

  Step 3 - Preview:
    python scripts/update_ist_coefficients.py --config smelt_update_config.json --preview

  Step 4 - Apply:
    python scripts/update_ist_coefficients.py --config smelt_update_config.json [--verbose]
"""

from __future__ import annotations

import argparse
import difflib
import json
import logging
import os
import re
import sys
from datetime import datetime
from typing import Any, Dict, List, Tuple

logger = logging.getLogger(__name__)

from ist_utils import (
    FAMILY_FOLDER_MAP,
    SUPPORTED_FAMILIES,
    classify_rail,
    detect_rail,
    find_coef_file,
    find_family_span,
    get_family_smelt_root,
    parse_vfes,
    read_smelt_coefficients,
    validate_pm_syntax,
)
import maths_ist_handler
import rist_handler
import rist_adaptive_handler

# Handler registry: family name -> handler module
FAMILY_HANDLERS = {
    'MATHS-IST': maths_ist_handler,
    'RIST': rist_handler,
    'RIST-Adaptive': rist_adaptive_handler,
}

# Standard directories (resolved from script location, works from any CWD)
_SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
_PROJECT_ROOT = os.path.dirname(_SCRIPT_DIR)
_CONFIG_DIR = os.path.join(_PROJECT_ROOT, 'config')


def _in_config_dir(name: str) -> str:
    """Resolve a bare name relative to the project's config/ directory.
    Paths with separators or absolute paths are returned as-is.
    """
    if os.path.isabs(name) or os.sep in name or '/' in name:
        return name
    return os.path.join(_CONFIG_DIR, name)


# ─────────────────────────────────────────────────────────────────
#  SMELT Coefficient Mapping
# ─────────────────────────────────────────────────────────────────

def build_smelt_map(
    smelt_entries: List[Dict],
    smelt_roots: Dict[str, str],
    family: str,
) -> Dict[Tuple[str, str], Dict[str, Any]]:
    """
    Build mapping: (ISTModeName, simplified_rail) -> {'coeffs': [...], 'folder_base': '...'}
    for a single family.

    smelt_roots maps family name -> resolved SMELT_fitting directory.
    Only entries tagged with the given family are processed.
    If multiple entries target the same (mode, rail), first entry wins.
    """
    smelt_root = smelt_roots.get(family, '')
    if not smelt_root or not os.path.isdir(smelt_root):
        logger.debug("%s: no SMELT root directory, skipping coefficient scan", family)
        return {}

    smelt_map: Dict[Tuple[str, str], Dict[str, Any]] = {}

    for entry in smelt_entries:
        entry_family = entry.get('family', '')
        if entry_family and entry_family != family:
            continue

        folder_base = entry.get('folder_base', '')
        ist_modes = entry.get('ist_modes', [])
        rail = detect_rail(folder_base)

        if not rail:
            logger.warning("Cannot detect rail from '%s', skipping", folder_base)
            continue

        coef_path = find_coef_file(smelt_root, folder_base)
        if not coef_path:
            logger.warning("No coef file found for '%s' in %s, skipping", folder_base, smelt_root)
            continue

        coeffs = read_smelt_coefficients(coef_path)
        logger.debug("Read coefficients from %s", os.path.basename(coef_path))
        logger.debug("  IST order: [%s]", ', '.join(coeffs))

        for mode in ist_modes:
            key = (mode, rail)
            if key not in smelt_map:
                smelt_map[key] = {'coeffs': coeffs, 'folder_base': folder_base}
                logger.debug("  Mapped: (%s, %s)", mode, rail)
            else:
                logger.debug("  Skipped duplicate: (%s, %s) already mapped", mode, rail)

    return smelt_map


# ─────────────────────────────────────────────────────────────────
#  File Update (multi-family)
# ─────────────────────────────────────────────────────────────────

def detect_indent(file_text: str, config_name: str, family: str = 'MATHS-IST') -> str:
    """Detect the indentation used for a family key within a config."""
    pat = re.compile(r'^([ \t]*)' + re.escape(f"'{family}'") + r'\s*=>\s*\{', re.MULTILINE)
    cfg_pat = re.compile(re.escape(f"'{config_name}'") + r"\s*=>\s*\{")
    cfg_m = cfg_pat.search(file_text)
    if not cfg_m:
        return '\t\t\t\t'

    m = pat.search(file_text, cfg_m.end())
    if m:
        return m.group(1)
    return '\t\t\t\t'


def apply_family_update(
    file_text: str,
    config_name: str,
    family: str,
    new_vfes: List[Dict[str, Any]],
) -> str:
    """Replace a family section for a specific config with new VFE blocks."""
    handler = FAMILY_HANDLERS.get(family)
    if not handler:
        logger.error("No handler for family '%s'", family)
        return file_text

    span_start, span_end = find_family_span(file_text, config_name, family)
    if span_start is None:
        logger.warning("Could not find %s section in config '%s'", family, config_name)
        return file_text

    indent = detect_indent(file_text, config_name, family)
    new_section = handler.generate_section(new_vfes, indent) + ','

    logger.debug("Replacing %s in '%s' (chars %d-%d, %d VFEs)",
                 family, config_name, span_start, span_end, len(new_vfes))

    return file_text[:span_start] + new_section + file_text[span_end:]


# ─────────────────────────────────────────────────────────────────
#  Excel Export
# ─────────────────────────────────────────────────────────────────

def _export_to_excel(pm_text: str, xlsx_path: str) -> None:
    """Export ist_settings .pm text to a formatted Excel workbook."""
    try:
        import openpyxl
        from openpyxl.styles import Font, Alignment, PatternFill
    except ImportError:
        logger.warning("openpyxl not installed, skipping Excel export. Install with: pip install openpyxl")
        return

    # --- helpers ---
    def _find_block(text, key, start=0):
        pattern = re.compile(rf"'{re.escape(key)}'\s*=>\s*\{{")
        match = pattern.search(text, start)
        if not match:
            return None
        brace_start = match.end() - 1
        depth = 0
        i = brace_start
        while i < len(text):
            ch = text[i]
            if ch == '{':
                depth += 1
            elif ch == '}':
                depth -= 1
                if depth == 0:
                    return match.start(), i + 1
            i += 1
        return None

    def _find_vfe_blocks(block_text):
        results = []
        pat = re.compile(r"'(VFE\d+)'\s*=>\s*\{")
        for m in pat.finditer(block_text):
            vfe_name = m.group(1)
            rel_start = m.start()
            brace_start = m.end() - 1
            depth = 0
            i = brace_start
            while i < len(block_text):
                ch = block_text[i]
                if ch == '{':
                    depth += 1
                elif ch == '}':
                    depth -= 1
                    if depth == 0:
                        results.append((vfe_name, rel_start, i + 1))
                        break
                i += 1
        return results

    def _parse_list(list_text):
        list_text = re.sub(r"#.*", "", list_text)
        raw = [item.strip() for item in list_text.split(",") if item.strip()]
        return [item.strip().strip("'").strip('"') for item in raw]

    def _extract_list(vfe_text, key):
        m = re.search(rf"'{re.escape(key)}'\s*=>\s*\[(.*?)\]", vfe_text, re.S)
        return _parse_list(m.group(1)) if m else []

    def _extract_single(vfe_text, key):
        m = re.search(rf"'{re.escape(key)}'\s*=>\s*'([^']*)'", vfe_text)
        return m.group(1).strip() if m else ""

    def _extract_coeffs(vfe_text):
        m = re.search(r"'Coeffs'\s*=>\s*\[(.*?)\]", vfe_text, re.S)
        return _parse_list(m.group(1)) if m else []

    def _list_top_keys(block_text):
        keys = []
        pat = re.compile(r"'([^']+)'\s*=>\s*\{")
        depth = 0
        depths = [0] * (len(block_text) + 1)
        for i, ch in enumerate(block_text):
            if ch == '{':
                depth += 1
            elif ch == '}':
                depth -= 1
            depths[i + 1] = depth
        for m in pat.finditer(block_text):
            if depths[m.start()] == 1:
                keys.append(m.group(1))
        return keys

    def _detect_source(vfe_text):
        return "SMELT" if '#SMELT' in vfe_text else "Safe"

    # --- build workbook ---
    data_block = _find_block(pm_text, "DataPointers")
    if not data_block:
        logger.warning("DataPointers block not found, skipping Excel export")
        return
    dp_start, dp_end = data_block
    dp_text = pm_text[dp_start:dp_end]
    configs = _list_top_keys(dp_text)

    wb = openpyxl.Workbook()
    families = ["MATHS-IST", "RIST", "RIST-Adaptive"]
    sheets = {}
    header_font = Font(bold=True)
    header_fill = PatternFill("solid", fgColor="D9E1F2")
    header_align = Alignment(horizontal="center", vertical="center", wrap_text=True)
    cell_align = Alignment(vertical="top", wrap_text=True)
    smelt_fill = PatternFill("solid", fgColor="C6EFCE")
    safe_fill = PatternFill("solid", fgColor="FCE4D6")

    for i, family in enumerate(families):
        ws = wb.active if i == 0 else wb.create_sheet(title=family)
        ws.title = family
        headers = ["Config", "VFE", "Source", "ISTModeNames",
                   "VoltageDomains", "Thermeqtype", "Variable", "Coeffs"]
        ws.append(headers)
        for col_idx in range(1, len(headers) + 1):
            cell = ws.cell(1, col_idx)
            cell.font = header_font
            cell.fill = header_fill
            cell.alignment = header_align
        ws.freeze_panes = "A2"
        sheets[family] = ws

    ws_modes = wb.create_sheet(title="ISTModeRows")
    mode_headers = ["Config", "TestType", "VFE", "Source", "ISTModeName",
                    "VoltageDomains", "Thermeqtype", "Variable", "Coeffs"]
    ws_modes.append(mode_headers)
    for col_idx in range(1, len(mode_headers) + 1):
        cell = ws_modes.cell(1, col_idx)
        cell.font = header_font
        cell.fill = header_fill
        cell.alignment = header_align
    ws_modes.freeze_panes = "A2"

    for cfg in configs:
        config_block = _find_block(pm_text, cfg)
        if not config_block:
            continue
        c_start, c_end = config_block
        config_text = pm_text[c_start:c_end]
        for family in families:
            fam_block = _find_block(config_text, family)
            if not fam_block:
                continue
            f_start, f_end = fam_block
            fam_text = config_text[f_start:f_end]
            for vfe_name, vfe_start, vfe_end in _find_vfe_blocks(fam_text):
                vfe_text = fam_text[vfe_start:vfe_end]
                modes = _extract_list(vfe_text, "ISTModeNames")
                domains = _extract_list(vfe_text, "VoltageDomains")
                thermeq = _extract_single(vfe_text, "Thermeqtype")
                variables = _extract_list(vfe_text, "Variable")
                coeffs = _extract_coeffs(vfe_text)
                source = _detect_source(vfe_text)
                row = [cfg, vfe_name, source, "|".join(modes),
                       "|".join(domains), thermeq, "|".join(variables), "|".join(coeffs)]
                ws_fam = sheets[family]
                ws_fam.append(row)
                row_fill = smelt_fill if source == "SMELT" else safe_fill
                for col_idx in range(1, len(row) + 1):
                    ws_fam.cell(ws_fam.max_row, col_idx).fill = row_fill

                for mode in modes if modes else [""]:
                    mode_row = [cfg, family, vfe_name, source, mode,
                                "|".join(domains), thermeq, "|".join(variables), "|".join(coeffs)]
                    ws_modes.append(mode_row)
                    for col_idx in range(1, len(mode_row) + 1):
                        ws_modes.cell(ws_modes.max_row, col_idx).fill = row_fill

    for ws in list(sheets.values()) + [ws_modes]:
        for row in ws.iter_rows(min_row=2, max_row=ws.max_row):
            for cell in row:
                cell.alignment = cell_align
        if ws.title == "ISTModeRows":
            widths = [24, 16, 10, 8, 40, 28, 16, 28, 60]
        else:
            widths = [24, 10, 8, 60, 28, 16, 28, 60]
        for idx, width in enumerate(widths, start=1):
            ws.column_dimensions[openpyxl.utils.get_column_letter(idx)].width = width

    wb.save(xlsx_path)


# ─────────────────────────────────────────────────────────────────
#  Main Update Logic
# ─────────────────────────────────────────────────────────────────

def _load_config(config_path: str) -> dict:
    """
    Load config from JSON or Excel file.

    Supports both .json and .xlsx formats. The xlsx format is generated
    by generate_smelt_config.py alongside the JSON and contains 3 sheets:
      - settings: key-value pairs (ist_base, smelt_root, target_configs, etc.)
      - smelt_entries: folder_base, ist_modes, note, candidates
      - user_groups: group_id, ist_modes
    """
    ext = os.path.splitext(config_path)[1].lower()

    if ext == '.json':
        with open(config_path, 'r', encoding='utf-8') as f:
            return json.load(f)

    if ext == '.xlsx':
        try:
            import openpyxl
        except ImportError:
            logger.error("openpyxl required to read .xlsx config. Install: pip install openpyxl")
            return {}

        wb = openpyxl.load_workbook(config_path, data_only=True)
        config = {}

        # ── Read settings sheet ──
        if 'settings' in wb.sheetnames:
            ws = wb['settings']
            kv = {}
            for row in ws.iter_rows(min_row=2, max_col=2, values_only=True):
                key, val = row
                if key:
                    kv[str(key).strip()] = str(val).strip() if val else ''

            # Per-family SMELT roots
            smelt_roots = {}
            for k, v in kv.items():
                if k.startswith('smelt_root_') and v:
                    fam = k[len('smelt_root_'):]
                    smelt_roots[fam] = v
            config['inputs'] = {
                'ist_base': kv.get('ist_base', 'ist_settings.pm'),
                'smelt_roots': smelt_roots if smelt_roots else {},
                'xlsx': kv.get('xlsx', 'IST_Modes_Support.xlsx'),
            }
            # Legacy single smelt_root fallback
            if not smelt_roots and kv.get('smelt_root'):
                config['inputs']['smelt_root'] = kv['smelt_root']
            target_configs_str = kv.get('target_configs', '')
            families_str = kv.get('target_families', kv.get('target_family', 'MATHS-IST'))
            families_list = [f.strip() for f in families_str.split('|') if f.strip()]
            config['target'] = {
                'configs': [c.strip() for c in target_configs_str.split('|') if c.strip()],
                'families': families_list,
            }

        # ── Read smelt_entries sheet ──
        entries = []
        if 'smelt_entries' in wb.sheetnames:
            ws = wb['smelt_entries']
            headers = [ws.cell(1, c).value for c in range(1, ws.max_column + 1)]
            col_map = {str(h).strip(): i for i, h in enumerate(headers) if h}

            for row in ws.iter_rows(min_row=2, max_col=ws.max_column, values_only=True):
                folder_base = str(row[col_map.get('folder_base', 0)] or '').strip()
                if not folder_base:
                    continue
                family_val = str(row[col_map.get('family', -1)] or '').strip() if 'family' in col_map else ''
                ist_modes_str = str(row[col_map.get('ist_modes', 1)] or '').strip()
                ist_modes = [m.strip() for m in ist_modes_str.split('|') if m.strip()]
                note = str(row[col_map.get('note', 2)] or '').strip()
                entry = {
                    'folder_base': folder_base,
                    'ist_modes': ist_modes,
                    'note': note,
                }
                if family_val:
                    entry['family'] = family_val
                entries.append(entry)
        config['smelt_entries'] = entries

        # ── Read user_groups sheet ──
        groups = []
        if 'user_groups' in wb.sheetnames:
            ws = wb['user_groups']
            for row in ws.iter_rows(min_row=2, max_col=2, values_only=True):
                group_id, ist_modes_str = row
                if ist_modes_str:
                    modes = [m.strip() for m in str(ist_modes_str).split('|') if m.strip()]
                    if modes:
                        groups.append({'ist_modes': modes})
        config['user_groups'] = groups

        logger.info("Loaded config from Excel: %s", config_path)
        return config

    logger.error("Unsupported config format '%s'. Use .json or .xlsx", ext)
    return {}


def run_update(
    config_path: str,
    dry_run: bool = False,
    preview: bool = False,
    diff: bool = False,
) -> int:
    """Apply SMELT coefficient updates based on config file."""

    # Load config (supports both .json and .xlsx)
    config = _load_config(config_path)
    if not config:
        return 1

    inputs = config.get('inputs', {})
    ist_base_path = inputs.get('ist_base', 'ist_settings.pm')
    target_configs = config.get('target', {}).get('configs', [])
    # Support both 'families' (list) and legacy 'family' (string)
    target = config.get('target', {})
    target_families = target.get('families', [])
    if not target_families:
        legacy = target.get('family', 'MATHS-IST')
        target_families = [legacy] if isinstance(legacy, str) else legacy
    smelt_entries = config.get('smelt_entries', [])
    user_groups = config.get('user_groups', [])

    # Resolve paths relative to config file directory
    config_dir = os.path.dirname(os.path.abspath(config_path))
    if not os.path.isabs(ist_base_path):
        ist_base_path = os.path.join(config_dir, ist_base_path)

    # Resolve per-family SMELT roots
    raw_smelt_roots = inputs.get('smelt_roots', {})
    smelt_roots: Dict[str, str] = {}
    for fam, root in raw_smelt_roots.items():
        if os.path.isabs(root):
            smelt_roots[fam] = root
        else:
            smelt_roots[fam] = os.path.join(config_dir, root)
    # Legacy single smelt_root: apply to all families
    if not smelt_roots and inputs.get('smelt_root'):
        legacy_root = inputs['smelt_root']
        if not os.path.isabs(legacy_root):
            legacy_root = os.path.join(config_dir, legacy_root)
        for fam in target_families:
            smelt_roots[fam] = legacy_root

    # Create timestamped output folder under pmsettings_IST/output/
    timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
    output_folder = os.path.join(_PROJECT_ROOT, 'output', timestamp)
    output_pm_path = os.path.join(output_folder, 'ist_settings.pm')
    output_xlsx_path = os.path.join(output_folder, 'ist_settings.xlsx')

    # Validate
    if not os.path.isfile(ist_base_path):
        logger.error("Base file not found: %s", ist_base_path)
        logger.error("  Paths in config are resolved relative to config dir: %s", config_dir)
        return 1

    # Filter out entries with empty ist_modes
    valid_entries = [e for e in smelt_entries if e.get('ist_modes')]
    skipped = len(smelt_entries) - len(valid_entries)
    if skipped:
        logger.warning("Skipping %d entries with empty ist_modes", skipped)

    mode_label = "PREVIEW" if preview else ("DRY RUN" if dry_run else "APPLY")
    logger.info("Mode:      %s", mode_label)
    logger.info("Input:     %s", ist_base_path)
    for fam, root in smelt_roots.items():
        logger.info("SMELT:     %s -> %s", fam, root)
    if not preview and not dry_run:
        logger.info("Output:    %s/", output_folder)
    logger.info("Configs:   %s", target_configs)
    logger.info("Families:  %s", target_families)
    logger.info("Entries:   %d SMELT, %d groups", len(valid_entries), len(user_groups))
    logger.info("")

    # Read base file
    with open(ist_base_path, 'r', encoding='utf-8') as f:
        file_text = f.read()
    original_text = file_text

    # Build per-family SMELT coefficient maps
    logger.info("Reading SMELT coefficients...")
    smelt_maps: Dict[str, Dict[Tuple[str, str], List[str]]] = {}
    total_mapped = 0
    for family in target_families:
        fam_map = build_smelt_map(valid_entries, smelt_roots, family)
        smelt_maps[family] = fam_map
        total_mapped += len(fam_map)
        if fam_map:
            logger.info("  %s: %d (mode, rail) pairs", family, len(fam_map))
        else:
            logger.info("  %s: no SMELT coefficients (SMELT data may not exist yet)", family)

    logger.info("  Total: %d (mode, rail) pairs\n", total_mapped)

    if total_mapped == 0:
        logger.error("No valid SMELT coefficients found across any family. Check config entries.")
        return 1

    # Process each target config x family
    for config_name in target_configs:
        logger.info("Processing config: %s", config_name)

        for family in target_families:
            handler = FAMILY_HANDLERS.get(family)
            if not handler:
                logger.warning("No handler for family '%s', skipping", family)
                continue

            smelt_map = smelt_maps.get(family, {})
            if not smelt_map:
                logger.info("  %s: no SMELT data available, skipping", family)
                continue

            existing_vfes = parse_vfes(file_text, config_name, family=family)
            if not existing_vfes:
                logger.info("  %s: no VFEs found, skipping", family)
                continue

            total_modes = sum(len(v['modes']) for v in existing_vfes)
            logger.info("  %s: %d existing VFEs, %d mode entries", family, len(existing_vfes), total_modes)

            new_vfes = handler.plan_new_vfes(existing_vfes, smelt_map, user_groups)

            smelt_count = sum(1 for v in new_vfes if v['source'] == 'smelt')
            residual_count = sum(1 for v in new_vfes if v['source'] == 'residual')
            original_count = sum(1 for v in new_vfes if v['source'] == 'original')
            logger.info("    -> %d VFEs (%d SMELT, %d residual, %d original)",
                        len(new_vfes), smelt_count, residual_count, original_count)

            if not dry_run:
                file_text = apply_family_update(file_text, config_name, family, new_vfes)

        logger.info("")

    # Summary
    logger.info("=" * 60)
    logger.info("SUMMARY")
    logger.info("=" * 60)
    for config_name in target_configs:
        for family in target_families:
            vfes = parse_vfes(file_text, config_name, family=family)
            if vfes:
                logger.info("\n  %s / %s:", config_name, family)
                for v in vfes:
                    rail = classify_rail(v['voltage_domains'])
                    c = v['coeffs']
                    c_short = f"[{c[0]}, ... {c[-1]}]" if len(c) >= 2 else str(c)
                    logger.info("    %6s  %6s  %12s  modes=%d  coeffs=%s",
                                v['id'], rail, v['thermeqtype'], len(v['modes']), c_short)

    # ----- Validate output syntax -----
    if not dry_run:
        errors = validate_pm_syntax(file_text)
        if errors:
            for e in errors:
                logger.error("Syntax validation: %s", e)
            return 1

    # ----- Diff output -----
    if diff:
        diff_lines = difflib.unified_diff(
            original_text.splitlines(keepends=True),
            file_text.splitlines(keepends=True),
            fromfile='ist_settings.pm (original)',
            tofile='ist_settings.pm (updated)',
        )
        diff_text = ''.join(diff_lines)
        if diff_text:
            print(diff_text)
        else:
            print("No differences.")

    # ----- Preview mode: generate Excel only -----
    if preview:
        preview_xlsx = os.path.join(config_dir, f'ist_settings_preview_{timestamp}.xlsx')
        _export_to_excel(file_text, preview_xlsx)
        logger.info("\n" + "=" * 60)
        logger.info("PREVIEW Excel: %s", preview_xlsx)
        logger.info("Review this file. When satisfied, re-run without --preview to generate the .pm file.")
        return 0

    # ----- Dry run: no output -----
    if dry_run:
        logger.info("\nDRY RUN - no output files written")
        return 0

    # ----- Apply mode: create timestamped output folder -----
    os.makedirs(output_folder, exist_ok=True)

    # Write .pm file
    with open(output_pm_path, 'w', encoding='utf-8') as f:
        f.write(file_text)
    logger.info("\nWritten: %s", output_pm_path)

    # Generate Excel alongside
    _export_to_excel(file_text, output_xlsx_path)
    logger.info("Written: %s", output_xlsx_path)

    logger.info("\nOutput folder: %s", output_folder)
    return 0


# ─────────────────────────────────────────────────────────────────
#  CLI
# ─────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        description='Apply SMELT coefficients to IST settings',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples (works from any directory):
  # Just the config name -- automatically looks in config/
  python scripts/update_ist_coefficients.py --config smelt_update_config.json --dry-run
  python scripts/update_ist_coefficients.py --config smelt_update_config.json --preview
  python scripts/update_ist_coefficients.py --config smelt_update_config.json

  # Explicit path (also supported)
  python scripts/update_ist_coefficients.py --config C:/path/to/my_config.json

NOTE: Bare names (no path separators) are resolved relative to the project's
      config/ directory. Paths INSIDE the config file (ist_base, smelt_root)
      are resolved relative to the config file's directory automatically.
""")

    parser.add_argument('--config', type=str, required=True,
                        help='Config file name or path (bare name looks in config/)')
    parser.add_argument('--verbose', '-v', action='store_true',
                        help='Show detailed processing information')
    parser.add_argument('--dry-run', action='store_true',
                        help='Show update plan without writing output files')
    parser.add_argument('--preview', action='store_true',
                        help='Generate Excel preview only (no .pm output). '
                             'Review the Excel, then re-run without --preview to apply.')
    parser.add_argument('--diff', action='store_true',
                        help='Show unified diff of changes. Combines with --dry-run.')

    args = parser.parse_args()

    logging.basicConfig(
        level=logging.DEBUG if args.verbose else logging.INFO,
        format='%(message)s',
    )

    return run_update(
        config_path=_in_config_dir(args.config),
        dry_run=args.dry_run,
        diff=args.diff,
        preview=args.preview,
    )


if __name__ == '__main__':
    sys.exit(main())
